furniture/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('furniture_home.urls')),
]

furniture_home/urls.py
from django.urls import path
from . import views
app_name='furniture_home'
urlpatterns = [
    path('',views.index,name='ind'),
    path('home',views.home,name='hom'),
    path('bedroom',views.bed,name='bed'),
    path('livingroom',views.living,name='live'),
    path('about',views.about,name='abt'),
    path('contact',views.contact,name='con'),
    path('accessories',views.accessory,name='asry'),
]

furniture_home/models.py
from django.db import models

# Create your models here.

furniture_home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render (request,'index.html')

def home(request):
    return render (request,'home.html')

def bed(request):
    return render (request,'bedroom.html')

def living(request):
    return render (request,'livingroom.html')

def about(request):
   return render (request,'about.html')

def contact(request):
    return render (request,'contact.html')

def accessory(request):
    return render(request,'accessories.html')

furniture_home/templates/about.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>
    

    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>
<div id="about">
    <div id="aboutwrite"> <h1>About Us</h1>
        <h3>Providing our clients with the best the world has to offer in home furnishings & decor ... for less.</h3>
    </div>
    <div id="aboutpic"><img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2019/10/cropped-logov3.png?w=878&ssl=1" alt="" id="logopic">
    <p>your statisfaction is Our Priority</p></div>
</div>
    <div id="wrdpic">
     <div id="word"><h1 id="font">It started with an idea</h1>
       <p id="size"> Palace Home Furniture was started with the idea that hard working families deserve to own the best items without the typical high mark-ups that traditionally exist in the furniture industry. To bring the best items from the best manufacturers in the world and make them available to the marketplace for less than anyone else. Guaranteed.</p>
        
        </div>
    <div id="picture"><img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2019/10/about1.jpg?w=800&ssl=1" alt=""></div>
    </div>
    

    <div id="wrdpic2">
        <div id="picture2"><img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2019/10/about2.jpg?w=800&ssl=1" alt=""></div>
        <div id="word2"><h1 id="font">Streamlined for efficiency</h1>
           <p id="size"> Palace Home has worked from the bottom up. From negotiating with suppliers & vendors to freight companies and credit card processors we have utilized our combined 75 years of experience in the industry to streamline the entire furniture purchasing process and pass along the savings to our clients. </p> </div>
    </div>

    
</body>
</html>

furniture_home/templates/accessories.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>

    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>
    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>
    
    
    

    <div class="accessory"><h1>Accessories</h1></div>
   


    <div class="items">
        <div id="item1"></div>
        <div id="item2"></div>
        <div id="item3"></div>
        <div id="item4"></div>
    </div>

    <div class="itemwrite">
        <div class="write"><h3>Homey Design HD-1802-Mirror Burl & Metallic Antique Gold Finish European Luxury Furniture</h3>
       <p>$1,399.00</p> 
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1803-Mirror Burl & Metallic Antique Gold Finish European Luxury Furniture</h3>
            <p>$1,299.00</p>
            <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1806-Mirror Burl & Metallic Antique Gold Finish European Luxury Furniture</h3>
           <p>$1,299.00</p> 
            <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1861-Ceramic Vase & Pedestal White & Gold Finish Luxury Home Decor</h3>
            <p>$4,699.00</p>
        <button class="itembtn1"> Add to cart</button></div>
    </div>

    <br><br>
    <div class="items">
        <div id="item5"></div>
        <div id="item6"></div>
        <div id="item7"></div>
        <div id="item8"></div>
    </div>

    <div class="itemwrite">
        <div class="write"><h3>Homey Design HD-1862-Ceramic Vase & Pedestal White & Gold Finish Luxury Home Decor</h3>
            <p>$5,299.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1875-Ceramic Vase & Pedestal White & Gold Finish Luxury Home Decor</h3>
            <p>$979.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-8092-Mirror Satin Gold Finish European Luxury Furniture</h3>
            <p>$1,299.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1157-Display Antique Gold & Mahogany Finish Luxury Furniture</h3>
            <p>$2,599.00</p>
        <button class="itembtn1"> Add to cart</button></div>
    </div>
<br><br>
    <div class="items">
        <div id="item9"></div>
        <div id="item10"></div>
        <div id="item11"></div>
        <div id="item12"></div>
    </div>

    <div class="itemwrite">
        <div class="write"><h3>Homey Design HD-1176-Display Antique Gold & Mahogany Finish Luxury Furniture</h3>
            <p>$1,899.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1182-40''Lamp Antique White & Gold Finish Luxury Furniture</h3>
            <p>$2,299.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1207-Display Antique Silver & Golden Brown Finish European Luxury Furniture</h3>
            <p>$1,499.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1203-Display Antique Silver & Antique Gold Finish Luxury Furniture</h3>
            <p>$1,899.00</p>
        <button class="itembtn1"> Add to cart</button></div>
    </div>
</body>
</html>

furniture_home/templates/bedroom.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>

    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>
    
    

    <div id="bed">
        <div id="bedpic"><img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2019/09/HD-01-AC.jpg?w=1000&ssl=1" alt="" id="bpic"></div>
        <div id="bedbody"><h1>Homey Design HD-01 – Chair Champagne (Metallic Gold & Silver Blend) Finish European Luxury Furniture</h1>
           <p id="size"> $2,099.00
            Starting at $73/mo with Affirm. Prequalify now
            
            This beautiful Champagne type silver with golden hue finished hand carved solid wood balloon chair is a statement piece alone or as a pair of chairs to give your living area a breath of elegance you desire.
            
            Dimensions: 34in.x33in.x63in.
            Finish: Belle Silver
            Upholstered Material: Fabric
            Frame Material: Solid Wood
            Cubic FT: 41
            CBM: 1.15</p></div>

            <button id="crt">Add to cart</button>
    </div>
</body>
</html>

furniture_home/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>
    

    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>

    <div id="ct">

        <p><h1>Get in touch with us:</h1>

           <p><h2> Call: 626-391-9284 </h2></p>
            
           <h3> 19745 Colima Road <br>
            Rowland Heights, CA 91748</h3>
            
           <b> Email: info@palacehomefurniture.com </b></p>
    </div>
</body>
</html>

furniture_home/templates/home.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>
    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>


    <div id="homepic">
        <img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2022/07/7722promo.jpg?w=1169&ssl=1" alt="" id="hopic">
    </div>

    <div id="rooms">
        <div id="living"> <h1>Living Room</h1>
        <button class="btn">Shop Now</button></div>
        <div id="bdroom"><h1>Bed Room</h1>
            <button class="btn">Shop Now</button></div>
        <div id="dining"><h1>Dinning Room</h1>
            <button class="btn">Shop Now</button></div>
        </div>

       <div id="popular"> <h1>Popular Items</h1></div>

       <div id="parent">
        <div id="child1"></div>
        <div id="child2"></div>
        <div id="child3"></div>
        <div id="child4"></div>
       </div>

       <div id="parent2">
        
        <div class="kid"><p>LIVING ROOM, LIVING ROOM SETS</p>
        <h3>Homey Design HD-04-3pc Sofa Set Metallic Bright Gold Finish European Luxury Furniture</h3>
    <p>$8,999.00</p>
<button class="itembtn">Add to cart</button></div>

        <div class="kid"><p>LIVING ROOM, LIVING ROOM SETS,WHAT'S NEW</p>
        <h3>Homey Design HD-25-3pc Sofa Set Perfect Brown Finish European Luxury Furniture</h3>
    <p>$9,599.00</p>
    <button class="itembtn">Add to cart</button></div>

        <div class="kid"><p>DINING ROOM,DINNING ROOM SETS,WHAT'S NEW</p>
        <h3>Homey Design HD-1802-9pc Dining Set Perfect Brown Finish European Luxury Furniture</h3>
    <p>$18,999.00</p>
    <button class="itembtn">Add to cart</button></div>

        <div class="kid"><p>DINING ROOM,DINNING ROOM SETS,WHAT'S NEW</p>
        <h3>Homey Design HD-1803-5pc Round Dining Set Burl & Metallic Antique Gold Finish European Luxury Furniture</h3>
    <p>$10,999.00</p>
    <button class="itembtn">Add to cart</button></div>
       </div>
</body>
</html>

furniture_home/templates/index.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div>
        <ul>
      <li>  <img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2019/10/cropped-logov3.png?w=878&ssl=1" alt=""  id="imgpalace"></li>
    
     <li><div>
        <img src="https://th.bing.com/th/id/OIP.CZV-bnSKxR3ptJLCsYW0CQHaHa?w=170&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt="" id="imgact">
        My Account</div></li>
     <li><div>
        <img src="https://th.bing.com/th?q=Help+Symbol+Icon&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=en-IN&cc=IN&setlang=en&adlt=moderate&t=1&mw=247" alt="" class="imgs" id="imghelp">
        Customer help</div></li>
     <li><div>
        <img src="https://th.bing.com/th/id/OIP.fXzSB4qKJFvFEl29oTJr0AHaHa?w=193&h=193&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt="" class="imgs" id="imgout">
        Check Out </div></li>
     <li><div>
        <img src="https://th.bing.com/th/id/OIP.ckoRgLad27sQa_ZXE-BcdgHaHx?w=150&h=176&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt="" class="imgs" id="imgdollar">
        $0.00</div></li>
</ul>
</div>


<nav>
    <ul>
        <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
        <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
        <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
        <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
        <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
        <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
    </ul>
</nav>

<div id="freedelivery">
    <h2>
        FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
</div>

<div id="body">
    <img src="https://i0.wp.com/palacehomefurniture.com/wp-content/uploads/2022/07/7722promo.jpg?w=1169&ssl=1" alt="">
</div>


</body>
</html>

furniture_home/templates/livingroom.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/index.css' %}">
</head>
<body>
    <div id="freedelivery">
        <h2>
            FREE HOME DELIVERY FOR SOCIAL RESIDENTS !</h2>
    </div>
    

    <nav>
        <ul>
            <a href="{% url 'furniture_home:hom' %}"><li id="home">Home</li></a>
            <a href="{% url 'furniture_home:asry' %}"><li>Accessories</li></a>
            <a href="{% url 'furniture_home:bed' %}"><li>Bed Room</li></a>
            <a href="{% url 'furniture_home:live' %}"><li>Living Room</li></a>
            <a href="{% url 'furniture_home:abt' %}"><li>About</li></a>
            <a href="{% url 'furniture_home:con' %}"><li>Contact Us</li></a>
        </ul>
    </nav>
    <div class="accessory"><h1>Living Room</h1></div>
    
    
    <div class="items">
        <div id="itemI"></div>
        <div id="itemII"></div>
        <div id="itemIII"></div>
        <div id="itemIV"></div>
    </div>

    <div class="itemwrite">
        <div class="write"><h3>Homey Design HD-105-Love Seat Metallic Bright Gold Finish European Luxury Furniture</h3>
            <p>$2,899.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-105-Sofa Mettalic Bright Gold Finish European Luxury Furniture</h3>
            <p>$3,599.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-106-3PC SOFA SET Luxury </h3>
            <p>$7,899.00</p>
        <button class="itembtn1"> Add to cart</button></div>
        <div class="write"><h3>Homey Design HD-1803-Stool Burl & Mettalic Antique Gold Finish European Luxury Furniture</h3>
            <p>$1,199.00</p>
        <button class="itembtn1"> Add to cart</button></div>
</div>
<br><br>
<div class="items">
    <div id="itemV"></div>
    <div id="itemVI"></div>
    <div id="itemVII"></div>
    <div id="itemVIII"></div>
</div>

<div class="itemwrite">
    <div class="write"><h3>Homey Design HD-20301-3PC SOFA SET Exclusive Luxury</h3>
        <p>$7,799.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-20322-3PC SOFA SET Exclusive Luxury</h3>
        <p>$9,799.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-20339-3PC SOFA SET Exclusive Luxury</h3>
        <p>$8,999.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-20353-3PC SOFA SET Exclusive Luxury</h3>
        <p>$1,199.00</p>
    <button class="itembtn1"> Add to cart</button></div>
</div>
<br><br>
<div class="items">
    <div id="itemIX"></div>
    <div id="itemX"></div>
    <div id="itemXI"></div>
    <div id="itemXII"></div>
</div>

<div class="itemwrite">
    <div class="write"><h3>Homey Design HD-20353 Chair Metallic Silver Finish European Luxury Furniture</h3>
        <p>$2,099.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-2662 Love Seat Metallic Silver Finish European Luxury Furniture</h3>
        <p>$1,199.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-2662 Sofa Melattic Silver Finish European Luxury Furniture</h3>
        <p>$1,199.00</p>
    <button class="itembtn1"> Add to cart</button></div>
    <div class="write"><h3>Homey Design HD-2666 Chair Mettalic Briht Gold Finish European Luxury Furniture</h3>
        <p>$1,199.00</p>
    <button class="itembtn1"> Add to cart</button></div>
</div>
</body>
</html>